Repository EscolaDeSaudePublica/registrocovid-front, pull requests merged in 2020-10, with the labels that each got.

#114 Bugfix/suporte respiratorio
  .eslintrc
  package-lock.json
  package.json
  src/components/PrevJSON/PrevJSON.js
  src/components/PrevJSON/index.js
  src/components/RouteWithLayout/styles.js
  src/components/SnackBar/index.js
  src/components/index.js
  src/views/Complications/components/ComplicationsList/styles.js
  src/views/Complications/components/DefaultItem/DefaultItem.js
  src/views/Complications/components/NeurologicItem/NeurologicItem.js
  src/views/Complications/components/UTIItem/UTIItem.js
  src/views/ComplicationsVM/ComplicationsVM.js
  src/views/RespiratorySupport/RespiratorySupport.js
  src/views/RespiratorySupport/components/Canula.js
  src/views/RespiratorySupport/components/Cateter.js
  src/views/RespiratorySupport/components/DeleteIcon.js
  src/views/RespiratorySupport/components/Desmame.js
  src/views/RespiratorySupport/components/FieldComposerForm/FieldComposerForm.js
  src/views/RespiratorySupport/components/FieldComposerForm/index.js
  src/views/RespiratorySupport/components/FieldComposerItem/FieldComposerItem.js
  src/views/RespiratorySupport/components/FieldComposerItem/index.js
  src/views/RespiratorySupport/components/Form.js
  src/views/RespiratorySupport/components/Mascara.js
  src/views/RespiratorySupport/components/Pronacao.js
  src/views/RespiratorySupport/components/RespiratorySuportForm/RespiratorySuportForm.js
  src/views/RespiratorySupport/components/RespiratorySuportForm/index.js
  src/views/RespiratorySupport/components/RespiratorySuportForm/styles.js
  src/views/RespiratorySupport/components/RespiratorySuportFormList/RespiratorySuportFormList.js
  src/views/RespiratorySupport/components/RespiratorySuportFormList/index.js
  src/views/RespiratorySupport/components/RespiratorySuportItem/RespiratorySuportItem.js
  src/views/RespiratorySupport/components/RespiratorySuportItem/index.js
  src/views/RespiratorySupport/components/RespiratorySuportItemList/RespiratorySuportItemList.js
  src/views/RespiratorySupport/components/RespiratorySuportItemList/index.js
  src/views/RespiratorySupport/components/SelectRespiratorySuportType/SelectRespiratorySuportType.js
  src/views/RespiratorySupport/components/SelectRespiratorySuportType/index.js
  src/views/RespiratorySupport/components/SelectRespiratorySuportType/styles.js
  src/views/RespiratorySupport/components/Traqueostomia.js
  src/views/RespiratorySupport/components/Tubo.js
  src/views/RespiratorySupport/components/Ventilacao.js
  src/views/RespiratorySupport/components/index.js
  src/views/RespiratorySupport/schema.js
  src/views/RespiratorySupport/styles.js
Labels: bug

#149 #131 fixed the conditional to show date on RT-PCR form
  src/views/SpecificsTests/components/TesteRTCPRItem/TesteRTCPRItem.js
Labels: bug

#138 Bugfix/bug exames complementares
  src/views/ComplementaryTests/components/TestComplementaryForm/TestComplementaryForm.js
  src/views/ComplementaryTests/components/TestComplementatyItem/TestComplementatyItem.js
  src/views/ComplicationsVM/schema.js
  src/views/Hemodialise/components/HemodialiseForm/HemodialiseForm.js
  src/views/Outcome/components/OutcomeObitoForm/OutcomeObitoForm.js
  src/views/PhysicalExam/components/Form.js
Labels: bug

#152 Feature/validation identificacao paciente
  src/views/Comorbidities/Comorbidities.js
  src/views/GeneralInfo/GeneralInfo.js
  src/views/GeneralInfo/schema.js
  src/views/PatientIdentification/PatientIdentification.js
  src/views/PatientIdentification/schema.js
Labels: Validações de regras de negócio / campos

#153 Feature/validation sintomas iniciais
  src/views/InitialSymptoms/InitialSymptoms.js
  src/views/InitialSymptoms/schema.js
  src/views/ListPatients/ListPatients.js
  src/views/RelatedInfections/RelatedInfections.js
Labels: Validações de regras de negócio / campos

#129 Feature/validation info gerais
  src/views/Comorbidities/Comorbidities.js
  src/views/GeneralInfo/GeneralInfo.js
  src/views/GeneralInfo/schema.js
  src/views/InitialSymptoms/InitialSymptoms.js
Labels: MVP 2

#150 Feature/more validation info gerais
  src/views/GeneralInfo/schema.js
Labels: AJUSTES, Validações de regras de negócio / campos
